FROM ohmyfish/ohmyfish

ENV LASTUPDATE today
RUN fish -c "omf install bobthefish ;and \
    set -U theme_powerline_fonts no ;and \
    omf install jump ;and \
    omf install https://github.com/edc/bass"
